# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wavebreaker.root] run return 0
execute on passengers if entity @s[tag=aj.wavebreaker.data] unless data entity @s {data:{rigHash: '33d3bbcb1387df211a0153983269d4096358e744fdb88d9adf828fe6db283d74'}} on vehicle run function animated_java:wavebreaker/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1