# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.wavebreaker.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'wavebreaker', 'function_path': 'animated_java:wavebreaker/animations/bound/stop'}
tag @s remove aj.wavebreaker.animation.bound.playing
scoreboard players set @s aj.bound.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:wavebreaker/animations/bound/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only